/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_openrasp_v8_Context */

#ifndef _Included_com_baidu_openrasp_v8_Context
#define _Included_com_baidu_openrasp_v8_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_openrasp_v8_Context
 * Method:    setStringKeys
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_openrasp_v8_Context_setStringKeys
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_baidu_openrasp_v8_Context
 * Method:    setObjectKeys
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_openrasp_v8_Context_setObjectKeys
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_baidu_openrasp_v8_Context
 * Method:    setBufferKeys
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_openrasp_v8_Context_setBufferKeys
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
