/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_openrasp_v8_V8 */

#ifndef _Included_com_baidu_openrasp_v8_V8
#define _Included_com_baidu_openrasp_v8_V8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_openrasp_v8_V8
 * Method:    Initialize
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_v8_V8_Initialize
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_baidu_openrasp_v8_V8
 * Method:    Dispose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_v8_V8_Dispose
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_openrasp_v8_V8
 * Method:    CreateSnapshot
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_openrasp_v8_V8_CreateSnapshot
  (JNIEnv *, jclass, jstring, jobjectArray, jstring);

/*
 * Class:     com_baidu_openrasp_v8_V8
 * Method:    Check
 * Signature: (Ljava/lang/String;[BILcom/baidu/openrasp/v8/Context;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_baidu_openrasp_v8_V8_Check
  (JNIEnv *, jclass, jstring, jbyteArray, jint, jobject, jint);

/*
 * Class:     com_baidu_openrasp_v8_V8
 * Method:    ExecuteScript
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_openrasp_v8_V8_ExecuteScript
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
