/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_openrasp_v8_CrashReporter */

#ifndef _Included_com_baidu_openrasp_v8_CrashReporter
#define _Included_com_baidu_openrasp_v8_CrashReporter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_openrasp_v8_CrashReporter
 * Method:    install
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_openrasp_v8_CrashReporter_install
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
