/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_openrasp_NativePatches */

#ifndef _Included_com_baidu_openrasp_NativePatches
#define _Included_com_baidu_openrasp_NativePatches
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_openrasp_NativePatches
 * Method:    GetNetworkInterfaces
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_baidu_openrasp_NativePatches_GetNetworkInterfaces
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
